# Generated by Django 4.2.7 on 2024-02-12 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='data',
            name='salary',
        ),
    ]
