# Generated by Django 4.2.7 on 2024-02-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_data_designation_remove_data_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='gender',
            field=models.CharField(default='male', max_length=2080),
        ),
    ]
